### ISSUE TITLE
FormContent.render() does not receive 

### ISSUE THREAD

**Issue by valmynd** [feincms/form_designer#26]
as per the documentation of FeinCMS, content types are rendered in templates [via {{ content.render }}](https://pythonhosted.org/FeinCMS/contenttypes.html#rendering-contents-in-your-templates)

the problem: [the render() method of FormContent does take request as an (non-optional) argument](https://github.com/feincms/form_designer/blob/master/form_designer/contents.py#L46)

this is problematic, because when called from the template via {{ content.render }}, it does not work and the worst part is that no error is shown (somehow it gets swallowed by django template system).

a solution for this would be to add a process method like that...

```python
    def process(self, request, **kwargs):
        self.request = request
        return True # not shure about that line^^
```

... and use self.request instead of that parameter instead

```python
    def render(self, *args, **kwargs):
        form_class = self.form.form()
        prefix = 'fc%d' % self.id
        formcontent = self.request.POST.get('_formcontent')

        if self.request.method == 'POST' and (
                not formcontent or formcontent == smart_text(self.id)):
            form_instance = form_class(self.request.POST, prefix=prefix)

            if form_instance.is_valid():
                return self.process_valid_form(
                    self.request, form_instance, **kwargs)
        else:
            form_instance = form_class(prefix=prefix)

        return render_to_string(
            self.template,
            {
                'content': self,
                'form': form_instance,
            },
            request=self.request)
```

this works for me with Django 1.10.5 and FeinCMS 1.13.1

**Comment by matthiask** [comment]
Thanks! Yeah, it's documented that `render()` must work without arguments, and that is obviously not the case here.

The whole form processing should go into `process(self, request)`, and `render()` should only return the results of the call above *if* there are any. OTOH backwards compatibility is a thing so maybe your suggestion is better. 

(The `return True` line in `process` is incorrect, because we are not handling any extra paths after the page URL in this case, as for example the application content does.)

Do you want to submit a pull request? I'd appreciate it very much. Thanks!
